//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ball_of_Duty_Server.Persistence
{
    using System;
    using System.Collections.Generic;

    public partial class Player
    {
        public int Id { get; set; }
        public string Nickname { get; set; }
    
        public virtual Account Account { get; set; }

        private static int amountPlayers = 0; // Lige nu bliver det ikke persisteret..

        public Player(int id)
        {
            Id = id;
        }

        public static Player CreatePlayer()
        {
            return new Player(amountPlayers++);
        }
    }
}
